default-color: GOLD
prefix-max-length: 5
prefix-min-length: 2
#单位分钟
delete-guild-cooldown: 21600
# 若不开启 只会在stop服务器时保存
# 定时保存 防止多次读写文件
auto-save:
  enabled: true
  # 多久保存一次
  minutes: 30

default-guild-config:
  enabled: true
  # 创建日期 用于设置多久可以解散
  create-time: ""
  uuid: ""
  # 公会名
  prefix: ""
  # 会长名
  owner: ""
  # 领地名
  res: ""
  # 公会成员
  player-list: []
  color: GOLD
  apply-players: []
database:
  enabled: false
  host: "localhost"
  port: "3306"
  database: "torosamy_guild"
  username: "root"
  password: "root"