name: TorosamyGuild
main: net.torosamy.torosamyGuild.TorosamyGuild
version: '${project.version}'
author: '${plugin.yml.author}'
website: '${plugin.yml.website}'
api-version: '${plugin.yml.api}'
depend:
  - TorosamyCore
  - Residence
  - Vault